package com.ltp.houseofcodeevaluation.repository;

import android.net.Uri;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.auth.UserInfo;

import java.time.LocalDate;
import java.util.Date;

/**
 * definition of a chat message in the system
 */
public class Message {
    private String userName;
    private String avatarUri;
    private String text;
    private Date date;
    private String imageUri;

    public Message() {}

    /**
     * The default constructor for new messages, most properties are autogenerated
     * @param text the message
     */
    public Message(String text) {
        for (UserInfo profile : FirebaseAuth.getInstance().getCurrentUser().getProviderData()) {
            this.userName = profile.getDisplayName();
            this.avatarUri = profile.getPhotoUrl().toString();
        }
        this.text = text;
        this.date = new Date();
    }

    public Message(Uri uri) {
        for (UserInfo profile : FirebaseAuth.getInstance().getCurrentUser().getProviderData()) {
            this.userName = profile.getDisplayName();
            this.avatarUri = profile.getPhotoUrl().toString();
        }
        this.text = null;
        this.date = new Date();
        this.imageUri = uri.toString();
    }

    public Message(String userName, String avatarUri, String text, Date date, String imageUri) {
        this.userName = userName;
        this.avatarUri = avatarUri;
        this.text = text;
        this.date = date;
        this.imageUri = imageUri;
    }

    public String getUserName() {
        return userName;
    }

    public String getAvatarUri() {
        return avatarUri;
    }

    public String getText() {
        return text;
    }

    public Date getDate() {
        return date;
    }

    public Uri getImageUri() {
        if (imageUri != null) {
            return Uri.parse(imageUri);
        }
        return null;
    }
}
